import { Creator } from '../types';

export const creators: Creator[] = [
  { name: 'Bella Poarch', handle: '@bellapoarch', followers: 94000000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Bella_Poarch_2021.png' },
  { name: 'Niana Guerrero', handle: '@nianaguerrero', followers: 42300000, imageUrl: 'https://cdn.tatlerasia.com/tatlerasia/i/2025/06/29213800-niana-guerrero-4-edit_cover_1067x1600.jpg' },
  { name: 'Andrea Brillantes', handle: '@blythe', followers: 20100000, imageUrl: 'https://static.wikia.nocookie.net/abscbn/images/8/8e/Andrea_Brillantes.jpg' },
  { name: 'Ivana Alawi', handle: '@ivanaalawi', followers: 19900000, imageUrl: 'https://media.philstar.com/photos/2022/05/27/vana_2022-05-27_16-23-08.jpg' },
  { name: 'Vice Ganda', handle: '@unkabogableviceganda', followers: 18100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Vice_Ganda_in_Tarlac_%28cropped%29.jpg' },
  { name: 'Sanya Lopez', handle: '@sanya_lopez', followers: 16100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Sanya_Lopez.jpg' },
  { name: 'Kyline Alcantara', handle: '@itskylinealcantara3', followers: 15900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Kyline_Alcantara.jpg' },
  { name: 'Kathryn Bernardo', handle: '@bernardokath', followers: 14900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Kathryn_Bernardo_in_2023.jpg' },
  { name: 'Catriona Gray', handle: '@catriona_gray', followers: 13300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Catriona_Gray_in_2023_%28cropped%29.jpg' },
  { name: 'Joshua Garcia', handle: '@iam.joshuagarcia', followers: 12900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Joshua_Garcia_2022.jpg' },
  { name: 'Liza Soberano', handle: '@lizaasoberano', followers: 12300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Liza_Soberano_in_February_2023.jpg' },
  { name: 'Maymay Entrata', handle: '@maymayentrata', followers: 12100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Maymay_Entrata.jpg' },
  { name: 'Heart Evangelista', handle: '@lme85', followers: 11000000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Heart_Evangelista_in_2022.jpg' },
  { name: 'Ranz Kyle', handle: '@ranzkyle', followers: 10400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Ranz_Kyle_2018.jpg' },
  { name: 'Kim Chiu', handle: '@kimchiu', followers: 10200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Kim_Chiu_in_2023.jpg' },
  { name: 'Anne Curtis', handle: '@annecurtissmith', followers: 9600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Anne_Curtis_in_2023.jpg' },
  { name: 'Donnalyn Bartolome', handle: '@donnalyn', followers: 9200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Donnalyn_Bartolome_at_the_unveiling_of_the_new_%27Viva_Hotbabes%27_and_the_launch_of_the_%27V-MAX%27_streaming_service.jpg' },
  { name: 'Alex Gonzaga', handle: '@Mscathygonzaga', followers: 8800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Alex_Gonzaga_at_the_presscon_of_her_movie_%27Single_Bells%27.jpg' },
  { name: 'Francine Diaz', handle: '@francinediaz', followers: 8500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Francine_Diaz_in_2023.jpg' },
  { name: 'Daniel Padilla', handle: '@supremoe', followers: 8100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Daniel_Padilla_at_the_%27A_Very_Good_Girl%27_premiere_night_%28cropped%29.jpg' },
  { name: 'Bretman Rock', handle: '@bretmanrock', followers: 15300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Bretman_Rock_2021.jpg' },
  { name: 'Jelai Andres', handle: '@jelaiandrestiktok', followers: 10800000, imageUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_kU55t8f5nJCk2VQuw3w4t2n-6uSxEE8VOeW9d_2Q=s900-c-k-c0x00ffffff-no-rj' },
  { name: 'Zeinab Harake', handle: '@zeinabharake', followers: 12500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Zeinab_Harake.jpg' },
  { name: 'Herlene Budol', handle: '@herlene_budol', followers: 10100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Herlene_Budol_in_2023.jpg' },
  { name: 'Toni Fowler', handle: '@tonifowler', followers: 11200000, imageUrl: 'https://pbs.twimg.com/media/F31nFm8aYAAQ13H.jpg' },
  { name: 'James Reid', handle: '@jamesreid', followers: 5200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/88/James_Reid_2023.jpg' },
  { name: 'Nadine Lustre', handle: '@nadine', followers: 7100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Nadine_Lustre_2023.jpg' },
  { name: 'Pia Wurtzbach', handle: '@piawurtzbach', followers: 7900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Pia_Wurtzbach_in_2023.jpg' },
  { name: 'Maine Mendoza', handle: '@mainemendoza', followers: 6400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Maine_Mendoza_at_the_press_conference_for_%27Jack_Em_Popoy%27.jpg' },
  { name: 'Alden Richards', handle: '@aldenrichards', followers: 6100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Alden_Richards_in_2023.jpg' },
  { name: 'AC Bonifacio', handle: '@acbonifacio', followers: 8300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/AC_Bonifacio.jpg' },
  { name: 'Yeng Constantino', handle: '@yengconstantino', followers: 5800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Yeng_Constantino_in_2018.jpg' },
  { name: 'Janella Salvador', handle: '@janellasalvador', followers: 5500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Janella_Salvador_in_2023.jpg' },
  { name: 'Seth Fedelin', handle: '@sethfedelin', followers: 7700000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Seth_Fedelin_in_2023.jpg' },
  { name: 'Maja Salvador', handle: '@majasalvador', followers: 5300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Maja_Salvador_in_2023.jpg' },
  { name: 'Mimiyuuuh', handle: '@mimiyuuuh', followers: 4500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Mimiyuuuh_in_2023.jpg' },
  { name: 'Sarah Geronimo', handle: '@sarahgeronimo', followers: 5000000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Sarah_Geronimo_in_2023.jpg' },
  { name: 'Moira Dela Torre', handle: '@moiradelatorre', followers: 4800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Moira_Dela_Torre_in_2023.jpg' },
  { name: 'Chie Filomeno', handle: '@chiefilomeno', followers: 7600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Chie_Filomeno_in_2023.jpg' },
  { name: 'Jake Zyrus', handle: '@jakezyrus', followers: 1100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Jake_Zyrus.png' },
  { name: 'Maris Racal', handle: '@marisracal', followers: 4700000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Maris_Racal_in_2023.jpg' },
  { name: 'Bianca Umali', handle: '@bianxa', followers: 6900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Bianca_Umali_in_2023.jpg' },
  { name: 'Miguel Tanfelix', handle: '@migueltanfelix', followers: 6800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Miguel_Tanfelix.jpg' },
  { name: 'Gabbi Garcia', handle: '@gabbigarcia', followers: 4600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Gabbi_Garcia_in_2023.jpg' },
  { name: 'Bea Alonzo', handle: '@beaalonzo', followers: 4400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Bea_Alonzo_in_2023.jpg' },
  { name: 'Enrique Gil', handle: '@enriquegil', followers: 4300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Enrique_Gil_at_the_2016_Star_Magic_All-Star_Basketball_Game.jpg' },
  { name: 'Denise Laurel', handle: '@d_laurel', followers: 2300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Denise_Laurel_2022.jpg' },
  { name: 'Angel Locsin', handle: '@angellocsin', followers: 3900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Angel_Locsin_2018.jpg' },
  { name: 'Marian Rivera', handle: '@marianrivera', followers: 3800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Marian_Rivera_in_2023.jpg' },
  { name: 'Dingdong Dantes', handle: '@dingdongdantes', followers: 3700000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Dingdong_Dantes_in_2023.jpg' },
  { name: 'Vhong Navarro', handle: '@vhongnavarro', followers: 3600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Vhong_Navarro_in_2023.jpg' },
  { name: 'Jhong Hilario', handle: '@jhonghilario', followers: 3500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Jhong_Hilario_in_2023.jpg' },
  { name: 'Ryan Bang', handle: '@ryanbang', followers: 3400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Ryan_Bang_in_2023.jpg' },
  { name: 'Ion Perez', handle: '@ionperez', followers: 3300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Ion_Perez_in_2023.jpg' },
  { name: 'Karylle', handle: '@anakarylle', followers: 2500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Karylle_in_2023.jpg' },
  { name: 'Jugs Jugueta', handle: '@jugsjugsjugs', followers: 1200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Jugs_Jugueta_in_2023.jpg' },
  { name: 'Teddy Corpuz', handle: '@teddycorpuz', followers: 1100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Teddy_Corpuz_in_2023.jpg' },
  { name: 'Regine Velasquez', handle: '@reginevelasquez', followers: 2000000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Regine_Velasquez_in_2023.jpg' },
  { name: 'Ogie Alcasid', handle: '@ogiealcasid', followers: 1900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Ogie_Alcasid_in_2023.jpg' },
  { name: 'Jolina Magdangal', handle: '@jolinamagdangal', followers: 1800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Jolina_Magdangal_in_2023.jpg' },
  { name: 'Karla Estrada', handle: '@karlaestrada', followers: 1700000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Karla_Estrada_2016.jpg' },
  { name: 'Melai Cantiveros', handle: '@melaicantiveros', followers: 1600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Melai_Cantiveros_in_2023.jpg' },
  { name: 'Robi Domingo', handle: '@robidomingo', followers: 1500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Robi_Domingo_in_2023.jpg' },
  { name: 'Luis Manzano', handle: '@luckymanzano', followers: 1400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Luis_Manzano_2014.jpg' },
  { name: 'Jessy Mendiola', handle: '@jessymendiola', followers: 1300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Jessy_Mendiola.png' },
  { name: 'Billy Crawford', handle: '@billycrawford', followers: 1200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Billy_Crawford_2014.jpg' },
  { name: 'Coleen Garcia', handle: '@coleen', followers: 1100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Coleen_Garcia_at_the_2016_Star_Magic_All-Star_Basketball_Game.jpg' },
  { name: 'Derek Ramsay', handle: '@derekramsay', followers: 1000000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Derek_Ramsay_at_the_press_conference_for_%27The_Janice_and_Derek_Show%27.png/800px-Derek_Ramsay_at_the_press_conference_for_%27The_Janice_and_Derek_Show%27.png' },
  { name: 'Ellen Adarna', handle: '@ellenadarna', followers: 990000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Ellen_Adarna_at_the_press_conference_for_%27The_Janice_and_Derek_Show%27.png/800px-Ellen_Adarna_at_the_press_conference_for_%27The_Janice_and_Derek_Show%27.png' },
  { name: 'John Lloyd Cruz', handle: '@johnlloydcruz', followers: 980000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/John_Lloyd_Cruz_in_2023.jpg' },
  { name: 'Gloc-9', handle: '@glocdash9', followers: 970000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Gloc-9_2014.jpg' },
  { name: 'Arci Muñoz', handle: '@arcimunoz', followers: 2700000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Arci_Mu%C3%B1oz_at_the_2016_Star_Magic_All-Star_Basketball_Game.jpg' },
  { name: 'Yassi Pressman', handle: '@yassipressman', followers: 3200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Yassi_Pressman_in_2023.jpg' },
  { name: 'Sue Ramirez', handle: '@sueramirez', followers: 2900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Sue_Ramirez_in_2023.jpg' },
  { name: 'Loisa Andalio', handle: '@iamlDAb', followers: 4100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Loisa_Andalio_in_2023.jpg' },
  { name: 'Ronnie Alonte', handle: '@ralonte', followers: 4200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Ronnie_Alonte_in_2023.jpg' },
  { name: 'Julia Barretto', handle: '@juliabarretto', followers: 3100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Julia_Barretto_in_2023.jpg' },
  { name: 'Gerald Anderson', handle: '@geraldanderson', followers: 2800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Gerald_Anderson_at_the_2016_Star_Magic_All-Star_Basketball_Game.jpg' },
  { name: 'Carlo Aquino', handle: '@liwanagparakaykaren', followers: 1400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Carlo_Aquino_in_2023.jpg' },
  { name: 'Angelica Panganiban', handle: '@iamangelicap', followers: 2600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Angelica_Panganiban_at_the_2016_Star_Magic_All-Star_Basketball_Game.jpg' },
  { name: 'Coco Martin', handle: '@cocomartin', followers: 2400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Coco_Martin_in_2023.jpg' },
  { name: 'Jodi Sta.Maria', handle: '@jdistamaria', followers: 2200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Jodi_Sta._Maria_in_2023.jpg' },
  { name: 'Richard Gutierrez', handle: '@richardgutz', followers: 2100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Richard_Gutierrez_in_2023.jpg' },
  { name: 'Sarah Lahbati', handle: '@sarahlahbati', followers: 1900000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Sarah_Lahbati_in_2023.jpg' },
  { name: 'Paolo Ballesteros', handle: '@pochoy_29', followers: 1800000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Paolo_Ballesteros_at_the_press_conference_for_%27Jack_Em_Popoy%27.jpg' },
  { name: 'Dennis Trillo', handle: '@dennistrillo', followers: 1700000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Dennis_Trillo_in_2023.jpg' },
  { name: 'Jennylyn Mercado', handle: '@mercadojenny', followers: 1600000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Jennylyn_Mercado_in_2023.jpg' },
  { name: 'Tom Rodriguez', handle: '@akosimangtomas', followers: 1500000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Tom_Rodriguez_in_2019.jpg' },
  { name: 'Carla Abellana', handle: '@carlaangeline', followers: 1400000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Carla_Abellana_in_2023.jpg' },
  { name: 'Glaiza de Castro', handle: '@glaizaredux', followers: 1300000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Glaiza_de_Castro_in_2023.jpg' },
  { name: 'Rhian Ramos', handle: '@whianwamos', followers: 1200000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Rhian_Ramos_in_2023.jpg' },
  { name: 'Solenn Heussaff', handle: '@solenn', followers: 1100000, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Solenn_Heussaff_in_2019.jpg' },
  { name: 'Nico Bolzico', handle: '@nicobolzico', followers: 1000000, imageUrl: 'https://live.staticflickr.com/65535/52702755225_b441e8f244_b.jpg' },
];